### ISSUE TITLE
IE11やEdgeで日本語のファイルをダウンロードすると、ファイル名が文字化けします

### ISSUE THREAD

**Issue by tukiyo** [shimosyan/phpUploader#3]
(php側の設定の問題かもしれませんが)
chrome, firefoxでは正しくダウンロードが出来る日本語のファイル名のものが
IEだとダウンロード時に文字化けします。

ご確認いただけたら幸いです。

**Comment by shimosyan** [comment]
先ほど、対応したv1.1を公開しました。
ご指摘感謝いたします！
