### ISSUE TITLE
[FeatureRequest]レスポンシブデザインに対応してほしい

### ISSUE THREAD

**Issue by roflsunriz** [shimosyan/phpUploader#9]
タイトルが全てです。モバイルデバイスでアクセスするとファイル一覧が横長のままで使いにくいので縦長になるようにお願いします。因みにタイトルや説明部分はレスポンシブになっています。
![Untitled](https://github.com/shimosyan/phpUploader/assets/8847851/f06730e3-c0e5-4733-8466-86a58f76b8b0)

**Comment by roflsunriz** [comment]
@shimosyan

**Comment by shimosyan** [comment]
@roflsunriz 
すみません、大変お待たせしました。
レスポンシブですが、テーブルレンダリングでは「Datatables」というライブラリを使用しています。
「Datatables」はレスポンシブをサポートしているのですが、こちらの実装とバッティングしていて正常に描画ができないため、実装には相当な作業が必要であることがわかってるので意図して実装していません。

そのため大変申し訳ないのですが、対応予定はないです。

**Comment by roflsunriz** [comment]
了解しました。
